name: 'Slack Notify'
description: 'This action will send a notification to Slack'
author: 'rtCamp'
runs:
  using: 'docker'
  image: 'docker.io/shivani7948/test-slack:latest'
branding:
  icon: 'bell'
  color: 'yellow'
